- name: Copy shell script
  ansible.builtin.copy: 
  src: script.sh
  dest: /root/nextcloud/script.sh
  mode: '0755' 
  force: yes

- name: Set cronjob
  cron:
    name: Nextcloud Backup
    weekday: 6
    hour: 0
    minute: 0
    month: "*"
    state: present 
